name: Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: engineerd/setup-kind@v0.1.0
    - name: Run tests
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        pip install pytest pycodestyle
        pytest -v