name: kubegraph_tests
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]
    steps:
    - name: Python Code Style
      uses: andymckay/pycodestyle-action@0.1.3
    - name: PyTest
      uses: cclauss/GitHub-Action-for-pytest@0.5.0
      with:
        args: pytest -v
